### PR TITLE
Fix app icon lookup

### LINKED ISSUE #168: An icon file is picked at random when there are a few available
The issue can be observed when looking at https://github.com/quotient-im/Quaternion/runs/2156723257?check_suite_focus=true#step:17:7387:
```
-- Deploying files into AppDir root directory -- 
WARNING: No desktop file specified, using first desktop file found: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Deploying files to AppDir root using desktop file: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Deploying desktop file to AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop in/as /home/runner/work/Quaternion/Quaternion/install 
Deploying icon to AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/share/icons/hicolor/16x16/apps/quaternion.png 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/share/icons/hicolor/16x16/apps/quaternion.png in/as /home/runner/work/Quaternion/Quaternion/install 
Deploying AppRun symlink for executable in AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/bin/quaternion 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/bin/quaternion in/as /home/runner/work/Quaternion/Quaternion/install/AppRun 
```
and, a few days later with no changes to the relevant code, https://github.com/quotient-im/Quaternion/runs/2196823924?check_suite_focus=true#step:17:7414:
```
-- Deploying files into AppDir root directory -- 
WARNING: No desktop file specified, using first desktop file found: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Deploying files to AppDir root using desktop file: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Deploying desktop file to AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/share/applications/com.github.quaternion.desktop in/as /home/runner/work/Quaternion/Quaternion/install 
Deploying icon to AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/share/icons/hicolor/scalable/apps/quaternion.svgz 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/share/icons/hicolor/scalable/apps/quaternion.svgz in/as /home/runner/work/Quaternion/Quaternion/install 
Deploying AppRun symlink for executable in AppDir root: /home/runner/work/Quaternion/Quaternion/install/usr/bin/quaternion 
Creating symlink for file /home/runner/work/Quaternion/Quaternion/install/usr/bin/quaternion in/as /home/runner/work/Quaternion/Quaternion/install/AppRun 
```
(the latter further causing a failure because svgz files are not supposed to be used for desktop entries)

The problem is that [this code](https://github.com/linuxdeploy/linuxdeploy/blob/b6a1ba290e2e8fe232eac30e0af52e51c49b1131/src/core/appdir_root_setup.cpp#L54) does not provide a stable way of picking an icon file - it just picks the first file matching the pattern provided in the desktop file. If the desktop file only has a stem, anything will do; if it has a filename and an extension, the first file matching those in the icon paths will be ok, even if it's an 8x8 icon. It would be great if an icon with the best resolution was chosen instead (svg, if there's svg; or the largest png up to, say, 512x512). That implies reading the icon; but at the very least, it would be great to see the same icon being picked every time, otherwise AppImage generation may sometimes work, sometimes break as in the example above.

### PR DESCRIPTION
**Pull request by KitsuneRal**
Hope the code doesn't look too heavy-handed. if you'd prefer the less efficient but more compact "collection algebra" style (the way `deployIconPaths()` was done) instead of the current "visitor" style, let me know.  I stopped short of converting the `recursive` parameter to a template one (smth like `template <bool Recursive>`) since it is always passed as a constant; but that would mean a sweeping change across `listFilesInDirectory()` invocations. Next step is updating `AppDirRootSetup` to favour SVGs and somehow order PNGs.

Closes #168. Any feedback welcome.

### CODE REVIEW

**Comment by KitsuneRal** [comment]
Not sure why CI breaks but that doesn't seem to be related to my code, does it?

**Comment by TheAssassin** [comment]
Clearly not your code's fault. Seems like some hash of a source archive changed. Needs to be fixed on `master`.

**Comment by TheAssassin** [comment]
@KitsuneRal fixed on master, please rebase.

**Comment by KitsuneRal** [comment]
(Not sure why it was a force-push, the commits shouldn't have been overwritten.)

**Comment by KitsuneRal** [comment]
Ok, this is ready. I tried to make the algorithm not too convoluted but it does involve some path trickery; so I tried to extend the tests a bit, to cover at least some tricky (i.e. with PNGs of different sizes) code branches. I also tried to comment the code as much as possible; if something's still unclear, let me know.

**Comment by KitsuneRal** [comment]
Any chance to take a look?

**Comment by KitsuneRal** [comment]
Any news? The underlying problem intermittently breaks CI for my project, with no workaround available (`--icon-file` doesn't seem to help).

**Comment by TheAssassin** [comment]
Well, there's an obvious merge conflict. Please fix that.

**Comment by KitsuneRal** [comment]
Oh, sorry, missed this. Fixed now.

**Comment by KitsuneRal** [comment]
With the conflicts resolved (again), is there any obstacle to merge this?

**Review by TheAssassin — APPROVED** [review]

**Comment by TheAssassin** [comment]
Thanks a lot! I am so sorry for the long waiting time. This is a great improvement!

**Pull request merged**
