### PR TITLE
Filter out VDSO obj and interpreter

### PR DESCRIPTION
**Pull request by hdclark**
Increase filtering to anticipate glibc version 2.36 ldd output format change.

### CODE REVIEW

**Comment by TheAssassin** [comment]
I pushed a variant that fits my own code style better. I expect it to build just fine, so this bug should be resolved soon-ish.

**Comment by hdclark** [comment]
@TheAssassin Keeping code style consistent makes sense. Thanks for working on this!

**Comment by TheAssassin** [comment]
I need this PR open so I can merge the code. I pushed it on your branch.

**Comment by TheAssassin** [comment]
Binaries are on the way now! Please let me know whether they work on your test systems as well.

**Pull request merged**
