### PR TITLE
Fixes #167 - Bump patchelf version to 0.14.5

### LINKED ISSUE #167: Update patchelf to 0.10+
Request to update patchelf (currently using version 0.8) to something more modern (version 0.12).
to fix the issue found here:
https://github.com/NixOS/patchelf/issues/92

Currently replacing patchelf in my CI.

### PR DESCRIPTION
**Pull request by freakboy3742**
patchelf 0.8 is 9 years old; there have been a lot of bug fixes in the interim.

This has been submitted as a pull request so that I can get a CI build for testing purposes, because I can't find any documentation on the build process. The closest I've been able to get is to try and replicate the CI configuration locally, but I haven't had any success.

### CODE REVIEW

**Comment by freakboy3742** [comment]
It's also worth noting that AFAICT, the unit tests for linuxdeploy use patchelf... but use the *system* patchelf, which is 0.10 on Ubuntu 20.04 (i.e., `ubuntu-latest` on GitHub Actions). So - the unit tests for linuxdeploy are using a different version of patchelf to the version that is baked into the final linuxdeploy binary.

**Comment by TheAssassin** [comment]
I'm not entirely sure about it, but it sounds plausible. Could you fix that, please?

**Comment by freakboy3742** [comment]
Not easily. As I noted in the PR comment, the absence of any "how to contribute" guide means I haven't been able to successfully build linuxdeploy locally. This PR was a speculative bump to see if an updated patchelf version would address #204.

**Comment by TheAssassin** [comment]
You can usually get some inspiration from CI scripts. `env ARCH=x86_64 ci/build.sh` should do the trick, afterwards you will have a `linuxdeploy-x86_64.AppImage` which you can test.

**Comment by freakboy3742** [comment]
Believe me - that's what I've been doing. It's been a slow process of trying to work out what system dependencies are needed (like patchelf, apparently); combined with the fact that I'm developing on a Mac, through either Docker or a VM, so a bunch of the assumptions in the build script don't hold (e.g., that the size of the TMP drive isn't limited). 

That said - it looks like it might not be too difficult; reordering the sequence of events in the build script should do it, AFAICT. 

The bad news (for me, anyway) - the binary from the last CI run didn't fix #204. It built an AppImage, but the page offset bug still happened.

**Comment by TheAssassin** [comment]
I know that getting started with the development of AppImage related tools can be tough (although I think it is reasonable to expect some Linux-based system in those scripts). The combination of "lack of time" and "seeing third parties being interested in getting involved" is very effective at keeping me and others from documenting everything better. Contributions are highly appreciated!

**Comment by TheAssassin** [comment]
I guess since we can't tell whether this is going to cause issues (and important PRs like https://github.com/NixOS/patchelf/pull/202 have been merged upstream), we can just merge this. Should there be issues, we'll hear from the users.

**Comment by TheAssassin** [comment]
Thanks!

**Pull request merged**
