### PR TITLE
Fix for #133

### PR DESCRIPTION
**Pull request by X0rg**
Hello,

Finally, I figured a way to manage a temporary directory.
Let me know if you want to change `APPRUN_TMP_DIR` variable name to something else. Personally, I prefer uppercase for constant values.

### CODE REVIEW

**Comment by X0rg** [comment]
I just fixed the checksum issue in 5f09bc3. After some research, there is no worries about it, upstream modified the archive.

**Comment by X0rg** [comment]
Hello @TheAssassin,

Do I need to change something in this PR?

**Comment by TheAssassin** [comment]
I haven't been able to look at this yet. But I've seen it and it's on my list.

**Comment by X0rg** [comment]
As it was discussed in linuxdeploy/linuxdeploy-plugin-gtk#24, a temporary directory should be avoided at runtime.
Since we merged linuxdeploy/linuxdeploy-plugin-gtk#29, this PR is not required anymore.

@TheAssassin let me know if you are interested by cf5b4a1ce20fe0a8fdf35d7aaa81f14c094ce3a8 (move custom AppRun to a dedicated file): I can cherry pick it in a dedicated PR and adapt this commit if needed.

**Pull request closed without merging**
